apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-quarkus 
  description: Secure Supply Chain Example for Quarkus with Java   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags: ["java", "quarkus", "ssc", "sbom", "acs"] 
spec:
  type: service
  owner: user:guest 
  lifecycle: experimental
